USE [IISLogChopper]
GO;
SET ANSI_NULLS ON
GO;
SET QUOTED_IDENTIFIER ON
GO;
CREATE TABLE [dbo].[Logs_W3C]( [date] [nvarchar](250) NULL, [time] [nvarchar](250) NULL, [c-ip] [nvarchar](500) NULL, [cs-username] [nvarchar](500) NULL, [s-sitename] [nvarchar](500) NULL, [s-computername] [nvarchar](500) NULL, [s-ip] [nvarchar](500) NULL, [s-port] [nvarchar](500) NULL, [cs-method] [nvarchar](500) NULL, [cs-uri-stem] [nvarchar](500) NULL, [cs-uri-query] [nvarchar](max) NULL, [sc-status] [nvarchar](500) NULL, [sc-substatus] [nvarchar](500) NULL, [sc-win32-status] [nvarchar](500) NULL, [sc-bytes] [nvarchar](500) NULL, [time-taken] [nvarchar](500) NULL, [cs-version] [nvarchar](500) NULL, [cs-host] [nvarchar](500) NULL, [cs(User-Agent)] [nvarchar](500) NULL, [cs(Cookie)] [nvarchar](500) NULL, [cs(Referer)] [nvarchar](500) NULL, [RECORDER] [bigint] IDENTITY(1,1) NOT NULL, [TIMESTAMP] [timestamp] NOT NULL, [SID] [datetime] NULL ) ON [PRIMARY]
GO;
CREATE UNIQUE CLUSTERED INDEX [RECORDER] ON [dbo].[Logs_W3C] ( [RECORDER] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [C-IP] ON [dbo].[Logs_W3C] ( [c-ip] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [SC-STATUS] ON [dbo].[Logs_W3C] ( [sc-status] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [S-IP] ON [dbo].[Logs_W3C] ( [s-ip] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [TIME-TAKEN] ON [dbo].[Logs_W3C] ( [time-taken] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [DATE] ON [dbo].[Logs_W3C] ( [date] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [TIME] ON [dbo].[Logs_W3C] ( [time] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
SET ANSI_PADDING ON
GO;
CREATE NONCLUSTERED INDEX [DTTIME] ON [dbo].[Logs_W3C] ( [date] ASC, [time] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO;
CREATE OR ALTER VIEW vw_Logs_W3C AS SELECT * FROM Logs_W3C WITH(NOLOCK)
GO;